version: "3.1"

services:
  web:
    build: croquet
    image: croquet
    env_file:
      - default.env
      - secrets.env
    volumes:
      - static:/static
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - fullchain
      - privkey
    volumes:
      - static:/static

volumes:
  static:

secrets:
  fullchain:
    file: ./nginx/ssl/fullchain1.pem
  privkey:
    file: ./nginx/ssl/privkey1.pem

  