version: "3.1"

services:
  web:
    restart: unless-stopped
    build: croquet
    image: croquet-web
    secrets:
      - env_secrets
    environment:
      DJANGO_SETTINGS_MODULE: croquet.settings.production
      PYTHONUNBUFFERED: 1
      SECRETS_FILE: /run/secrets/env_secrets
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
      - certs:/certs
  nginx:
    restart: unless-stopped
    build: nginx
    image: nginx-croquet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/www/data/static
      - media:/www/data/media
      - certs:/certs

  certbot:
    # https://github.com/henridwyer/docker-letsencrypt-cron
    image: henridwyer/docker-letsencrypt-cron
    environment:
      DOMAINS: histoncroquet.org
      EMAIL: paul@rudin.co.uk
      CONCAT: "false"
      SEPARATE: "true"
    volumes:
      - certs:/certs
      

volumes:
  static:
  media:
  certs:


secrets:
  env_secrets:
    file: ./secrets.env
