version: "3.1"

services:
  web:
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

    volumes:
      - ./croquet:/usr/src/app
    environment:
      DJANGO_SETTINGS_MODULE: croquet.settings.dev

