version: "3.1"

services:
  web:
    build: croquet
    image: croquet-web
    env_file:
      - default.env
      - secrets.env
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
  nginx:
    build: nginx
    image: nginx-croquet
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - fullchain
      - privkey
    volumes:
      - static:/www/data/static
      - media:/www/data/media

volumes:
  static:
  media:

secrets:
  fullchain:
    file: ./nginx/ssl/fullchain1.pem
  privkey:
    file: ./nginx/ssl/privkey1.pem
